# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.7  

before_install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create --quiet --name TESTENV python=$TRAVIS_PYTHON_VERSION
  - source activate TESTENV
  - conda install -c conda-forge geopandas
  - conda info --all
  - conda list

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - flake8 .
  - coverage run --source urban_footprinter -m py.test

after_success:
  - coverage report -m
  - coveralls

# deploy new versions to PyPI
deploy:
  provider: pypi
  on:
    tags: true
    python: 3.7
  user: martibosch
  password:
    secure: TXJz+j4Ou76ooNxE7Pl/TqCdZWxeFgMukA+KReOad/VYET52RDSl2P084RvnOSRP/GJEebt3GhVXUi1t/8MRSR3IyO7qkixG4cqrN1L707y7P6nvZjaiagNAuLbo3oVX1x3TVWNvnSCZyjIlyA5jayCgDX60s0e4OqDpvTuHIRs0i3aQ0Z8MH+pWDepFUMTK7Xaiq2Asi9Yqq+JueCS6UocPtICxHhKrSsFxzUmz+Jw+GKHtFRZCVgblbPcJlohfkyxvGUD3P1n1he7Gr+ZHuaxSGXqM150sAl4AJEgZaSFGUpWPNJ83rdAVRrPav3T8lUw/QEGk+6wGEca4AP8o0b1tOJknxJa2y7OXvyjIvRYKHuEHkmK130xcPZnHTtwYTDYs1XTe5AIUuEBTES+9DMQh/dAV3dtD8Ljpap7vot7rpfHS5sREyWAZQ1py29SFMbkw9ied6RFFAPEa8Ma6R9wOVf3jefCcBUdh+76FnorpO6EYW+BzEyccU44vjvmgd6Iwglgu7Cxy69j6HabnoQ1DvLVgfeGXJY8GeZRutdjzYNDmWWMeGH87Netb7l6mzKUq1blG9sLZApb2JXDAlv/F+v5wHgnitZ/d4hp46ajJ57sSQAvDRAODmp44yuZzBvcWm3leZFmUoGTsnK9JhYnue46IuKCF2m6Pr5mz8mQ=
